version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: webapp/backend/Dockerfile
    container_name: sun_pharma_backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PORT=8000
    volumes:
      - ./processed_data:/app/processed_data:ro
      - ./outputs:/app/outputs:ro

  frontend:
    build:
      context: ./webapp/frontend
      dockerfile: Dockerfile
    container_name: sun_pharma_frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
